import Header from "@/components/ui/Header";
import Sidebar from "@/components/ui/Sidebar";
import type { Metadata } from "next";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
  <div className="grid lg:grid-cols-12 bg-primary-color w-full h-screen">
    <div className="col-span-2 hidden lg:block">
      <Sidebar/>
    </div>
    <div className="col-span-10  bg-[#f7f7f7] dark:bg-dark-mode lg:rounded-l-3xl h-screen overflow-y-auto">
      <Header/>
      {
        children
      }
    </div>
    
  </div>
  );
}
