import Header from '@/components/ui/Header';
import type { Metadata } from 'next';
import dynamic from 'next/dynamic';

export const metadata: Metadata = {
  title: 'TechTinker Lab',
  description: 'Generated by create next app',
};

const Sidebar = dynamic(()=>import('@/components/ui/Sidebar'),{ssr:false})
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="grid lg:grid-cols-12 bg-primary-color w-full h-screen">
      <div className="col-span-2 hidden lg:block">
        <Sidebar />
      </div>
      <div
        id="home-container"
        className="col-span-10  bg-[#f7f7f7] dark:bg-dark-mode lg:rounded-l-3xl h-screen overflow-y-auto overflow-x-hidden"
      >
        <Header />
        <div className="p-5 lg:p-10 ">{children}</div>
      </div>
    </div>
  );
}
